
name: exercice1
on: [push,pull_request] 
env:
  var1: "c'est un Push"
  var2: "c'est un pull_request"
jobs:
  job:
    runs-on: ubuntu-latest
    if: ${{ github.event.push}}
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script 
        run: echo $var1
  job:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request}}
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo $var2     

      
      
