name: Issue
on: 
  issues:
    branches: issue
    action: opened
env:
  var1: Issue créée
   
jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script 
        run: echo $var1 
 # job2:
 #   runs-on: ubuntu-latest
  #  steps:
      #- uses: actions/checkout@v3
     # - name: Run a one-line script 
      #  run: git branch issue